# Generated by Django 5.1.5 on 2025-01-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес доставки')),
                ('delivery_method', models.CharField(blank=True, help_text='Например: Самовывоз, Курьер, Почта России и т.д.', max_length=100, null=True, verbose_name='Способ доставки')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='Скидка (%)')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
                'db_table': 'tgshop_customer',
                'ordering': ['-created_at'],
            },
        ),
    ]
