# Generated by Django 5.1.5 on 2025-01-27 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='telegramsettings',
            table='models_telegramsettings',
        ),
    ]
