# Generated by Django 5.1.5 on 2025-01-27 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_alter_telegramsettings_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='telegramsettings',
            table='tgshop_telegramsettings',
        ),
    ]
