# Generated by Django 5.1.5 on 2025-01-27 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_alter_telegramsettings_table'),
    ]

  
