# Generated by Django 5.1.5 on 2025-01-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_alter_category_table_alter_operator_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramsettings',
            name='about',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='О магазине'),
        ),
    ]
