# Generated by Django 5.1.5 on 2025-01-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_telegramsettings_about_alter_category_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='tgshop_category',
        ),
        migrations.AlterModelTable(
            name='operator',
            table='tgshop_operator',
        ),
        migrations.AlterModelTable(
            name='product',
            table='tgshop_product',
        ),
        migrations.AlterModelTable(
            name='productimage',
            table='tgshop_productimage',
        ),
    ]
