# Generated by Django 5.1.5 on 2025-01-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_alter_category_table_alter_operator_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramsettings',
            name='bonus',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Бонусная система'),
        ),
        migrations.AddField(
            model_name='telegramsettings',
            name='ship_pay',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Доставка и оплата'),
        ),
        migrations.AlterField(
            model_name='telegramsettings',
            name='about',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='О магазине'),
        ),
    ]
